/**
 * State Machine for Door + Key + Box Cinematic Overlay
 */
export const DOOR_INTRO_STATES = {
  INITIALIZING: 'INITIALIZING',
  DOOR_IDLE: 'DOOR_IDLE',
  EXPLORING: 'EXPLORING',
  BOXES_VISIBLE: 'BOXES_VISIBLE',
  SEARCHING: 'SEARCHING',
  BOX_OPENING: 'BOX_OPENING',
  KEY_REVEALED: 'KEY_REVEALED',
  KEY_PICKED: 'KEY_PICKED',
  RETURNING_TO_DOOR: 'RETURNING_TO_DOOR',
  KEY_APPROACHING_LOCK: 'KEY_APPROACHING_LOCK',
  KEY_SNAPPING: 'KEY_SNAPPING',
  KEY_INSERTED: 'KEY_INSERTED',
  UNLOCKING: 'UNLOCKING',
  UNLOCKED: 'UNLOCKED',
  DOOR_OPENING: 'DOOR_OPENING',
  DOOR_OPEN: 'DOOR_OPEN',
  ENTERING_DOOR: 'ENTERING_DOOR',
  HANDOFF: 'HANDOFF',
  COMPLETE: 'COMPLETE'
}

/**
 * Valid transitions table for explicit state safety
 */
export const VALID_DOOR_TRANSITIONS = {
  [DOOR_INTRO_STATES.INITIALIZING]: [DOOR_INTRO_STATES.DOOR_IDLE, DOOR_INTRO_STATES.COMPLETE],
  [DOOR_INTRO_STATES.DOOR_IDLE]: [DOOR_INTRO_STATES.EXPLORING, DOOR_INTRO_STATES.KEY_PICKED, DOOR_INTRO_STATES.COMPLETE],
  [DOOR_INTRO_STATES.EXPLORING]: [DOOR_INTRO_STATES.BOXES_VISIBLE, DOOR_INTRO_STATES.DOOR_IDLE, DOOR_INTRO_STATES.COMPLETE],
  [DOOR_INTRO_STATES.BOXES_VISIBLE]: [DOOR_INTRO_STATES.SEARCHING, DOOR_INTRO_STATES.BOX_OPENING, DOOR_INTRO_STATES.DOOR_IDLE, DOOR_INTRO_STATES.COMPLETE],
  [DOOR_INTRO_STATES.SEARCHING]: [DOOR_INTRO_STATES.BOX_OPENING, DOOR_INTRO_STATES.DOOR_IDLE, DOOR_INTRO_STATES.COMPLETE],
  [DOOR_INTRO_STATES.BOX_OPENING]: [DOOR_INTRO_STATES.KEY_REVEALED, DOOR_INTRO_STATES.SEARCHING, DOOR_INTRO_STATES.BOXES_VISIBLE, DOOR_INTRO_STATES.COMPLETE],
  [DOOR_INTRO_STATES.KEY_REVEALED]: [DOOR_INTRO_STATES.KEY_PICKED, DOOR_INTRO_STATES.COMPLETE],
  [DOOR_INTRO_STATES.KEY_PICKED]: [DOOR_INTRO_STATES.RETURNING_TO_DOOR, DOOR_INTRO_STATES.KEY_APPROACHING_LOCK, DOOR_INTRO_STATES.COMPLETE],
  [DOOR_INTRO_STATES.RETURNING_TO_DOOR]: [DOOR_INTRO_STATES.DOOR_IDLE, DOOR_INTRO_STATES.KEY_APPROACHING_LOCK, DOOR_INTRO_STATES.COMPLETE],
  [DOOR_INTRO_STATES.KEY_APPROACHING_LOCK]: [DOOR_INTRO_STATES.KEY_SNAPPING, DOOR_INTRO_STATES.UNLOCKING, DOOR_INTRO_STATES.DOOR_OPENING, DOOR_INTRO_STATES.KEY_PICKED, DOOR_INTRO_STATES.COMPLETE],
  [DOOR_INTRO_STATES.KEY_SNAPPING]: [DOOR_INTRO_STATES.KEY_INSERTED, DOOR_INTRO_STATES.UNLOCKING, DOOR_INTRO_STATES.DOOR_OPENING, DOOR_INTRO_STATES.COMPLETE],
  [DOOR_INTRO_STATES.KEY_INSERTED]: [DOOR_INTRO_STATES.UNLOCKING, DOOR_INTRO_STATES.DOOR_OPENING, DOOR_INTRO_STATES.COMPLETE],
  [DOOR_INTRO_STATES.UNLOCKING]: [DOOR_INTRO_STATES.UNLOCKED, DOOR_INTRO_STATES.DOOR_OPENING, DOOR_INTRO_STATES.COMPLETE],
  [DOOR_INTRO_STATES.UNLOCKED]: [DOOR_INTRO_STATES.DOOR_OPENING, DOOR_INTRO_STATES.ENTERING_DOOR, DOOR_INTRO_STATES.COMPLETE],
  [DOOR_INTRO_STATES.DOOR_OPENING]: [DOOR_INTRO_STATES.DOOR_OPEN, DOOR_INTRO_STATES.ENTERING_DOOR, DOOR_INTRO_STATES.HANDOFF, DOOR_INTRO_STATES.COMPLETE],
  [DOOR_INTRO_STATES.DOOR_OPEN]: [DOOR_INTRO_STATES.ENTERING_DOOR, DOOR_INTRO_STATES.HANDOFF, DOOR_INTRO_STATES.COMPLETE],
  [DOOR_INTRO_STATES.ENTERING_DOOR]: [DOOR_INTRO_STATES.HANDOFF, DOOR_INTRO_STATES.COMPLETE],
  [DOOR_INTRO_STATES.HANDOFF]: [DOOR_INTRO_STATES.COMPLETE],
  [DOOR_INTRO_STATES.COMPLETE]: []
}

export function isValidDoorTransition(current, next) {
  if (next === DOOR_INTRO_STATES.COMPLETE) return true
  const allowed = VALID_DOOR_TRANSITIONS[current] || []
  return allowed.includes(next)
}
