/**
 * Pure State Machine for Cinematic Introduction Lifecycle
 */
export const INTRO_STATES = {
  INITIALIZING: 'INITIALIZING',
  DOOR_LOCKED: 'DOOR_LOCKED',
  SCROLLING_TO_BOXES: 'SCROLLING_TO_BOXES',
  SEARCHING_FOR_KEY: 'SEARCHING_FOR_KEY',
  KEY_FOUND: 'KEY_FOUND',
  KEY_DRAGGING: 'KEY_DRAGGING',
  KEY_INSERTED: 'KEY_INSERTED',
  DOOR_UNLOCKING: 'DOOR_UNLOCKING',
  DOOR_OPENING: 'DOOR_OPENING',
  ENTERING_DARKNESS: 'ENTERING_DARKNESS',
  DISTANT_LIGHT: 'DISTANT_LIGHT',
  LIGHT_APPROACHING: 'LIGHT_APPROACHING',
  WHITE_FLASH: 'WHITE_FLASH',
  RETURN_TO_DARKNESS: 'RETURN_TO_DARKNESS',
  TORCH_AVAILABLE: 'TORCH_AVAILABLE',
  TORCH_IGNITION: 'TORCH_IGNITION',
  TORCH_LIT: 'TORCH_LIT',
  SEARCHING_FOR_CAMPFIRE: 'SEARCHING_FOR_CAMPFIRE',
  CAMPFIRE_IGNITING: 'CAMPFIRE_IGNITING',
  CAMPFIRE_LIT: 'CAMPFIRE_LIT',
  HOMEPAGE_ILLUMINATING: 'HOMEPAGE_ILLUMINATING',
  INTRO_COMPLETED: 'INTRO_COMPLETED'
}

// Valid transitions for each state to prevent accidental state skips
const VALID_TRANSITIONS = {
  [INTRO_STATES.INITIALIZING]: [INTRO_STATES.DOOR_LOCKED, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.DOOR_LOCKED]: [INTRO_STATES.SCROLLING_TO_BOXES, INTRO_STATES.SEARCHING_FOR_KEY, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.SCROLLING_TO_BOXES]: [INTRO_STATES.SEARCHING_FOR_KEY, INTRO_STATES.DOOR_LOCKED, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.SEARCHING_FOR_KEY]: [INTRO_STATES.KEY_FOUND, INTRO_STATES.DOOR_LOCKED, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.KEY_FOUND]: [INTRO_STATES.KEY_DRAGGING, INTRO_STATES.KEY_INSERTED, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.KEY_DRAGGING]: [INTRO_STATES.KEY_FOUND, INTRO_STATES.KEY_INSERTED, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.KEY_INSERTED]: [INTRO_STATES.DOOR_UNLOCKING, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.DOOR_UNLOCKING]: [INTRO_STATES.DOOR_OPENING, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.DOOR_OPENING]: [INTRO_STATES.ENTERING_DARKNESS, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.ENTERING_DARKNESS]: [INTRO_STATES.TORCH_AVAILABLE, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.TORCH_AVAILABLE]: [INTRO_STATES.TORCH_IGNITION, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.TORCH_IGNITION]: [INTRO_STATES.TORCH_LIT, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.TORCH_LIT]: [INTRO_STATES.SEARCHING_FOR_CAMPFIRE, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.SEARCHING_FOR_CAMPFIRE]: [INTRO_STATES.CAMPFIRE_IGNITING, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.CAMPFIRE_IGNITING]: [INTRO_STATES.SEARCHING_FOR_CAMPFIRE, INTRO_STATES.CAMPFIRE_LIT, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.CAMPFIRE_LIT]: [INTRO_STATES.HOMEPAGE_ILLUMINATING, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.HOMEPAGE_ILLUMINATING]: [INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.INTRO_COMPLETED]: []
}

export function canTransition(currentState, nextState) {
  if (nextState === INTRO_STATES.INTRO_COMPLETED) return true
  const allowed = VALID_TRANSITIONS[currentState]
  return allowed ? allowed.includes(nextState) : false
}
