/**
 * Pure State Machine for Cinematic Introduction Lifecycle
 */
export const INTRO_STATES = {
  INITIALIZING: 'INITIALIZING',
  TEXT_STRANGER: 'TEXT_STRANGER',
  TEXT_FOLLOW_ME: 'TEXT_FOLLOW_ME',
  TUNNEL_SCROLLING: 'TUNNEL_SCROLLING',
  TRANSITIONING_TO_DARKNESS: 'TRANSITIONING_TO_DARKNESS',

  TORCH_AVAILABLE: 'TORCH_AVAILABLE',
  TORCH_IGNITION: 'TORCH_IGNITION',
  TORCH_LIT: 'TORCH_LIT',
  SEARCHING_FOR_CAMPFIRE: 'SEARCHING_FOR_CAMPFIRE',
  CAMPFIRE_IGNITING: 'CAMPFIRE_IGNITING',
  CAMPFIRE_LIT: 'CAMPFIRE_LIT',
  HOMEPAGE_ILLUMINATING: 'HOMEPAGE_ILLUMINATING',
  INTRO_COMPLETED: 'INTRO_COMPLETED'
}

// Flexible transitions to guarantee user scroll and touch interactions are never blocked
const VALID_TRANSITIONS = {
  [INTRO_STATES.INITIALIZING]: [INTRO_STATES.TEXT_STRANGER, INTRO_STATES.TEXT_FOLLOW_ME, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.TEXT_STRANGER]: [INTRO_STATES.TEXT_FOLLOW_ME, INTRO_STATES.TUNNEL_SCROLLING, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.TEXT_FOLLOW_ME]: [INTRO_STATES.TUNNEL_SCROLLING, INTRO_STATES.TRANSITIONING_TO_DARKNESS, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.TUNNEL_SCROLLING]: [INTRO_STATES.TRANSITIONING_TO_DARKNESS, INTRO_STATES.TORCH_AVAILABLE, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.TRANSITIONING_TO_DARKNESS]: [INTRO_STATES.TORCH_AVAILABLE, INTRO_STATES.INTRO_COMPLETED],

  [INTRO_STATES.TORCH_AVAILABLE]: [INTRO_STATES.TORCH_IGNITION, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.TORCH_IGNITION]: [INTRO_STATES.TORCH_LIT, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.TORCH_LIT]: [INTRO_STATES.SEARCHING_FOR_CAMPFIRE, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.SEARCHING_FOR_CAMPFIRE]: [INTRO_STATES.CAMPFIRE_IGNITING, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.CAMPFIRE_IGNITING]: [INTRO_STATES.SEARCHING_FOR_CAMPFIRE, INTRO_STATES.CAMPFIRE_LIT, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.CAMPFIRE_LIT]: [INTRO_STATES.HOMEPAGE_ILLUMINATING, INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.HOMEPAGE_ILLUMINATING]: [INTRO_STATES.INTRO_COMPLETED],
  [INTRO_STATES.INTRO_COMPLETED]: []
}

export function canTransition(currentState, nextState) {
  if (nextState === INTRO_STATES.INTRO_COMPLETED) return true
  const allowed = VALID_TRANSITIONS[currentState]
  return allowed ? allowed.includes(nextState) : false
}
